id: I1DDB06D4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T06:31:02+00:00'
last_modified: '2022-06-08T01:04:59.982902+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W384
  title: གསུང་འབུམ། མཁས་གྲུབ་རྗེ། （ཞོལ་པར་མ། ལྡི་ལིར་བསྐྱར་པར་བརྒྱབ་པ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    F1D3:
      image_group_id: I1KG956
      title: ''
      total_pages: 1186
      order: 1
      base_file: F1D3.txt
    44A6:
      image_group_id: I1KG957
      title: ''
      total_pages: 1118
      order: 2
      base_file: 44A6.txt
    A7A4:
      image_group_id: I1KG958
      title: ''
      total_pages: 970
      order: 3
      base_file: A7A4.txt
    A980:
      image_group_id: I1KG959
      title: ''
      total_pages: 1036
      order: 4
      base_file: A980.txt
    6FB8:
      image_group_id: I1KG960
      title: ''
      total_pages: 942
      order: 5
      base_file: 6FB8.txt
    '7994':
      image_group_id: I1KG961
      title: ''
      total_pages: 942
      order: 6
      base_file: 7994.txt
    C8C8:
      image_group_id: I1KG962
      title: ''
      total_pages: 964
      order: 7
      base_file: C8C8.txt
    0B67:
      image_group_id: I1KG963
      title: ''
      total_pages: 890
      order: 8
      base_file: 0B67.txt
    '2918':
      image_group_id: I1KG964
      title: ''
      total_pages: 990
      order: 9
      base_file: 2918.txt
    885E:
      image_group_id: I1KG965
      title: ''
      total_pages: 1006
      order: 10
      base_file: 885E.txt
    4F92:
      image_group_id: I1KG966
      title: ''
      total_pages: 902
      order: 11
      base_file: 4F92.txt
    48B8:
      image_group_id: I1KG967
      title: ''
      total_pages: 946
      order: 12
      base_file: 48B8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
