id: P004438
initial_creation_type: ocr
source_metadata:
  id: bdr:W384
  title: གསུང་འབུམ། མཁས་གྲུབ་རྗེ། （ཞོལ་པར་མ། ལྡི་ལིར་བསྐྱར་པར་བརྒྱབ་པ།）
  author: ''
  volumes:
    e37b51c42b2b43f39ebe371677c57ed4:
      image_group_id: I1KG956
      title: ''
      volume_number: 1
      total_pages: 1186
      base_file: v001.txt
    13895a14ab704a61a67ca6dc21838176:
      image_group_id: I1KG957
      title: ''
      volume_number: 2
      total_pages: 1118
      base_file: v002.txt
    ba2050b6dcbf49189de30b8190d26282:
      image_group_id: I1KG958
      title: ''
      volume_number: 3
      total_pages: 970
      base_file: v003.txt
    703efe6210b9445fa2422ee799c5f8e4:
      image_group_id: I1KG959
      title: ''
      volume_number: 4
      total_pages: 1036
      base_file: v004.txt
    64ed43e5022d43d292ae6bf2518684cd:
      image_group_id: I1KG960
      title: ''
      volume_number: 5
      total_pages: 942
      base_file: v005.txt
    bd5c6bccf69946f6b28671201110f403:
      image_group_id: I1KG961
      title: ''
      volume_number: 6
      total_pages: 942
      base_file: v006.txt
    777c1a25cd7d4c78b03acbe5fec38873:
      image_group_id: I1KG962
      title: ''
      volume_number: 7
      total_pages: 964
      base_file: v007.txt
    a89963d9cae043e2aa25ec1ddfa39b96:
      image_group_id: I1KG963
      title: ''
      volume_number: 8
      total_pages: 890
      base_file: v008.txt
    76d2f293a87c424d8fdf8aac182fa320:
      image_group_id: I1KG964
      title: ''
      volume_number: 9
      total_pages: 990
      base_file: v009.txt
    c0e27b5ecb9e42b5938a2e2686e67922:
      image_group_id: I1KG965
      title: ''
      volume_number: 10
      total_pages: 1006
      base_file: v010.txt
    aa76ad789f25441cb7b5e6110e7b488a:
      image_group_id: I1KG966
      title: ''
      volume_number: 11
      total_pages: 902
      base_file: v011.txt
    d6b6b4b41bd44fa88b869022d10360b2:
      image_group_id: I1KG967
      title: ''
      volume_number: 12
      total_pages: 946
      base_file: v012.txt
